######################################################################
# Automatically generated by qmake (2.01a) lun. nov. 11 15:20:27 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . vue
INCLUDEPATH += . vue

# Input
HEADERS += vue/mainwindow.h \
    modele/brique.h \
    modele/joueur.h
SOURCES += main.cpp vue/mainwindow.cpp \
    modele/brique.cpp \
    modele/joueur.cpp
